import { Env } from "@shared/types/evn.types";
import { parseBoolean } from "@shared/utils/parse-boolean.util";

const { env } = process;

export default (): Env => ({
  NODE_ENV: env.NODE_ENV,

  ALLOWED_ORIGIN: env.ALLOWED_ORIGIN,

  APP_PORT: parseInt(env.APP_PORT),
  APP_HOST: env.APP_HOST,
  APP_URL: env.APP_URL,

  POSTGRES_PORT: parseInt(env.POSTGRES_PORT),
  POSTGRES_HOST: env.POSTGRES_HOST,
  POSTGRES_USER: env.POSTGRES_USER,
  POSTGRES_PASSWORD: env.POSTGRES_PASSWORD,
  POSTGRES_DB: env.POSTGRES_DB,
  POSTGRES_URL: env.POSTGRES_URL,

  REDIS_PORT: parseInt(env.REDIS_PORT),
  REDIS_HOST: env.REDIS_HOST,
  REDIS_USER: env.REDIS_USER,
  REDIS_PASSWORD: env.REDIS_PASSWORD,
  REDIS_URL: env.REDIS_URL,

  COOKIE_SECRET: env.COOKIE_SECRET,

  SESSION_SECRET: process.env.SESSION_SECRET,
  SESSION_DOMAIN: env.SESSION_DOMAIN,
  SESSION_NAME: env.SESSION_NAME,
  SESSION_FOLDER: process.env.SESSION_FOLDER,
  SESSION_SECURE: parseBoolean(env.SESSION_SECRET),
  SESSION_HTTP_ONLY: parseBoolean(env.SESSION_HTTP_ONLY),

  GRAPHQL_PREFIX: env.GRAPHQL_PREFIX,
});
